#
# Macro file for "Hadr04.cc"
# (can be run in batch, without graphic)
#
# neutron 100 MeV; all processes
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat G4_WATER
/testhadr/det/setSize 200 m
#
#/testhadr/phys/thermalScattering true
#
/random/setSeeds 0 1
/run/initialize
#
/process/list
#
/particle/createAllIsomer
/gun/particle neutron
/gun/energy 400 MeV
#
/analysis/setFileName water400seedout
/analysis/h1/set 1  100  0. 200. none	#nb colli >1eV
/analysis/h1/set 2  100  0. 5. m	#track len >1eV
/analysis/h1/set 3  100  0. 1. ns	#time of flight >1eV
/analysis/h1/set 4  100  0. 10000. none	#nb colli <1eV
/analysis/h1/set 5  100  0. 100. m	#track len <1eV
/analysis/h1/set 6  100  0. 20. ns	#time of flight <1eV
/analysis/h1/set 7  100  0. 500. keV	#energy dist <1eV
/analysis/h1/set 8  100  0. 2. ms  #time of nCapture
#
/run/printProgress 200
#
/run/beamOn 2000
